# This automatically builds and releases the documentation
name: Build Documentation
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: ["release"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pygmentize
        run: pip3 install Pygments

      - name: Find the latex files
        id: pl
        run: python3 ./BuildTools/findfiles.py

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.file_count }} documentation files."

      - name: Install latex
        run: |
          winget install -e --id ChristianSchenk.MiKTeX

      - name: Build the documentation
        run: python3 ./BuildTools/builddocs.py

      - name: Display the size of the documentation
        run: ls -lh output.zip

      - name: Release Documentation
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "APSC 258 Documentation"
          files: |
            output.zip
