# This automatically builds and releases the documentation
name: Build Documentation
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  create:
    tags:
      - v*

  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        run: |
          sudo apt-get update && sudo apt-get install -y python3.7
          sudo apt-get install -y python3-pip

      - name: Install pygmentize
        run: sudo pip3 install Pygments

      - name: Find the latex files
        id: pl
        run: sudo python3 ./BuildTools/findfiles.py

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.file_count }} documentation files."

      - name: Install latex
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
          echo "deb http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt-get update
          sudo apt-get install -y miktex
          sudo miktexsetup --shared=yes finish
          sudo initexmf --admin --set-config-value [MPM]AutoInstall=1

      - name: Build the documentation
        run: sudo python3 ./BuildTools/builddocs.py

      - name: Display the size of the documentation
        run: ls -lh output.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./output.zip
